[project]
name = "GFMs"
dynamic = ["version"]
description = "Critical analysis of Genomic Foundation Models."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.1.0",
    "biopython>=1.87",
    "ckatorch>=1.0.2",
    "datasets>=4.5.0",
    "huggingface-hub>=1.3.4",
    "ipython>=9.12.0",
    "joblib>=1.5.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
    "tokenizers>=0.22.2",
    "torch>=2.10.0",
    "torchmetrics>=1.9.0",
    "transformers>=5.0.0",
    "wandb>=0.25.0",
]
